### ISSUE TITLE
Generate entity-relationship diagram for system

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-ics4u-2015/attendance#1]

**Comment by rgordonathome** [comment]
Resolved. ER diagram is here. 

https://github.com/rsgc-ics4u-2015/attendance/blob/master/db/attendance.mwb

**Comment by rsgc-power-r** [comment]
![screen shot 2015-11-18 at 11 48 07 am](https://cloud.githubusercontent.com/assets/14296590/11247484/4dba35cc-8dea-11e5-85d5-ae8336616787.png)
This is a screenshot of the ER diagram. This solves issue #1.
