### ISSUE TITLE
Convert entity-relationship diagram to database schema

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-ics4u-2015/attendance#2]
Use MySQL workbench to generate the schema.

**Comment by rsgc-power-r** [comment]
ER diagram is here.
https://github.com/rsgc-ics4u-2015/attendance/blob/master/db/attendance.mwb

![screen shot 2015-11-18 at 11 52 08 am](https://cloud.githubusercontent.com/assets/14296590/11247621/d93a607c-8dea-11e5-83e0-0970e9119fda.png)
This is a screenshot of the database schematic.
This fixes issue #2.
