### ISSUE TITLE
Get list of attendance codes that need to be in system

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-ics4u-2015/attendance#3]
See Ms. Fitzpatrick or Ms. Wagar – ask for printout of possible codes.

**Comment by rsgc-power-r** [comment]
Resolved Issue #3

Attendance codes:
P - Parent Excused
PI - Parent Excused (Illness)
PD - Parent Excused (Doctor)
PO - Parent Excused (Other/Dentist)
LU - Late
LE - Late Excused
E - School Excused
EDP - Early Dismissal by Parent
EDS - Early Dismissal by School
SU - Suspended
CA - Counselling Appointment
